### ISSUE TITLE
Caveats in installing the library 

### ISSUE THREAD

**Issue by marcoaaz** [RomanJuranek/graph-segmentation#1]
## Hi Roman,

I got your technique working in a new conda environment. Nice work. 

For future users though, I would like to add a list of caveats. The install guide is missing:

-Noticing that we need to use pip not conda (which is trapped in 'solving' the environment)
-The preferred Python version. I worked fine with Python 3.7 but I read somewhere that they used Python 3.6.7 64-bit ('TESCAN')
-explaining to downgrade protobuf: pip install protobuf==3.20.*
-including scikit-learn in requirements.txt
-regressing to h5py 2.10.0 (not the default 3.8.0) to avoid: AttributeError: 'str' object has no attribute 'decode' (see https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi)
-mentioning that for running the 'example.ipynb' you need a ipykernel on your environment (https://pypi.org/project/ipykernel/).

Please, could you upload the code that you used to build/train the autoencoder following VGG? I do not have the mineral spectra database from Hrstka (2018) and yours as well. Please, upload to a cloud service them if you have them available to be able to reproduce your research. For instance, I am interested in encoding RAMAN spectra and making my own spectral library (random sampled and simulated) as you did.

Cordially,
Marco
